### PR TITLE
Update iced

### PR DESCRIPTION
**Pull request by git-f0x**
~This currently panics, since it seems to enter unreachable code in the `view` function in `app.rs` (similar to pop-os/cosmic-greeter#149).~

Edit: This now doesn't panic (enabling multi-window seems to fix it), but the OSDs show up as just a dot.

### CODE REVIEW

**Comment by ids1024** [comment]
Yeah, looks like the autosized layer-shell code that previously existed in `iced_sctk` (https://github.com/pop-os/iced/blob/061995084a5775b4fd7df63dda336be01ddf491c/sctk/src/application.rs#L2187-L2195) isn't implemented in the current `iced_winit` fork.

**Comment by git-f0x** [comment]
This now mostly works. The only issue is that the numbers for volume adjustment disappear (or get cut off) when a volume button is pressed a second time.

**Comment by ids1024** [comment]
Good question. Perhaps it should use `secure_input` if `echo` is `false`, and just `text_input` otherwise.

The polkit dialog also seems to no longer focus the text box immediately on start as it did before, and requires manually clicking on the text box.

**Comment by git-f0x** [comment]
>The polkit dialog also seems to no longer focus the text box immediately on start as it did before, and requires manually clicking on the text box.

That's also a reported issue after the App Library rebase, that the search bar isn't focused initially. So it might be something that needs to be fixed in libcosmic/iced.

**Comment by ids1024** [comment]
Looking at the documentation for the older and newer iced, it looks like `Task::batch` was changed to execute in parallel, when it was previously serial. So that change looks correct, and we'll want the same thing here.

**Comment by git-f0x** [comment]
I've been trying to do the same, but not quite sure where to chain the focus. Chaining it after `cmd` in the `new` method in `polkit_dialog` leads to borrowing issues. And I'm not seeing where else it could be placed.

**Comment by ids1024** [comment]
Hm, I guess it's not the same issue here, since cosmic-osd isn't using `text_input::focus` in a `batch` along with the `get_layer_surface`, but using it in `LayerEvent::Focused` and `polkit_agent_helper::Event::Complete`. That sounds like it should work...

**Comment by ids1024** [comment]
Looks like the `::Enter` event just wasn't been sent, so this code wasn't reached.

https://github.com/pop-os/iced/pull/195.

**Comment by ids1024** [comment]
I guess defaulting to `/usr/local` is conventional in most build systems? But yeah, it makes sense to match other Cosmic components.

**Comment by git-f0x** [comment]
The polkit dialog is now focused on launch!
This then seems to be fully functional.

**Review by ids1024 — APPROVED** [review]
Yep, seems good now. Thanks!

**Pull request merged**
