### PR TITLE
OSD Indicators

### PR DESCRIPTION
**Pull request by ids1024**
This adds OSD indicators for volume, mute, display brightness, keyboard brightness, and airplane mode.

For volume/mute, this has a thread using libpulse to monitor changes to the default sink. It may be good add a microphone volume option too.

For airplane mode, this uses a tokio task that polls `/dev/rfkill` and reads events from it. (If multiple devices change state at once, this should be atomic as implemented.) It considers airplane mode active if all devices are blocked in rfkill. This should match Gnome but may not fit expectation of airplane mode on other platforms (https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/issues/288). We'll also want to make sure applets and settings handle airplane mode consistently. (And monitor for changes similarly.)

Touchpad toggle isn't handled yet. We'll need something to handle `XF86TouchpadToggle` and disable touchpad devices in cosmic-comp, while also signally cosmic-osd to show an OSD? This could all be done with cosmic-config, but would make the setting persistent, which is normally not the expectation with this.

There are still some details I want to fix/adjust and some things I want to test before merging this.

### CODE REVIEW

**Comment by ryanabx** [comment]
I've been testing this today, and here are my thoughts:

> My device is an ASUS GA402RJ for reference, running Fedora 39 with [cosmic rpms](https://copr.fedorainfracloud.org/coprs/ryanabx/cosmic-epoch/) installed. Built cosmic-osd and usroverlayed it, removing the installed cosmic-osd with this one.

* On my device, when I use fn + f1 to unmute the speakers, the mute OSD is shown instead of an unmute one
* No osd shown when enabling airplane mode with fn + f12, but I'm assuming that's an ASUS issue and not one with this PR
* No osd shown when muting and unmuting my microphone using the dedicated key on my laptop (GNOME has an OSD for this)
* Can't modify volume with the volume OSD, but fine imo for a first implementation

**Comment by ids1024** [comment]
Yeah, unmuting needs to be handled properly, and this still needs support for microphone volume/mute.

For the airplane mode key, if it is disabling networking, that may be some hardware feature that isn't reported to the OS. If it does nothing, it's probably sending the XF86AirplaneMode keycode, which we may not handle yet.

**Comment by ryanabx** [comment]
> Yeah, unmuting needs to be handled properly, and this still needs support for microphone volume/mute.
> 
> 
> 
> For the airplane mode key, if it is disabling networking, that may be some hardware feature that isn't reported to the OS. If it does nothing, it's probably sending the XF86AirplaneMode keycode, which we may not handle yet.

Out of curiosity, where is the handling for all these key presses going to land into? I see volume changing key presses in cosmic comp config, and some mentions of brightness control in cosmic-settings-daemon

**Comment by ids1024** [comment]
Fixed the icons used for volume/mute states, added microphone volume. Also updated the polkit dialog to used the `dialog` widget from libcosmic.

**Review by mmstick — APPROVED** [review]

**Pull request merged**
